---
openapi: "3.0.3"
jsonSchemaDialect: "https://json-schema.org/draft/2020-12/schema"
info:
  title: "Violet API"
  version: "1.0.0"
  summary: "Swagger documentation for the Violet backend API"
  description: "Here you can find all the necessary endpoints to consume the Violet\
    \ API"
  termsOfService: "https://example.com"
  contact:
    name: "Gleb Gutnik"
  license:
    name: "Open license"
servers: []
paths:
  /api/v1/login:
    post:
      tags:
      - "Auth repository"
      summary: "Login"
      description: "Login a user with his username and password"
      parameters: []
      requestBody:
        description: "Login a user"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLoginRequest"
        required: true
      responses:
        "201":
          description: "User successfully logged in"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenData"
      deprecated: false
    parameters: []
  /api/v1/refresh:
    post:
      tags:
      - "Auth repository"
      summary: "Refresh"
      description: "Refresh JWT token"
      parameters: []
      requestBody:
        description: "Refresh a token"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshToken"
        required: true
      responses:
        "200":
          description: "Token successfully refreshed"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenData"
      deprecated: false
    parameters: []
  /api/v1/signup:
    post:
      tags:
      - "Auth repository"
      summary: "User signup"
      description: "Sign up a user with their email and password"
      parameters: []
      requestBody:
        description: "Register a user"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserData"
        required: true
      responses:
        "201":
          description: "User successfully registered"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignupResponse"
      deprecated: false
    parameters: []
  /api/v1/check-session:
    get:
      tags:
      - "Auth repository"
      summary: "Session check"
      description: "Check if the user's session is still valid"
      parameters: []
      responses:
        "201":
          description: "User's session is valid"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserData"
      deprecated: false
      security:
      - matchme-jwt-auth: []
    parameters: []
  /api/v1/notes:
    get:
      tags:
      - "Notes repository"
      summary: "Notes for user"
      description: "All notes for the given user"
      parameters: []
      responses:
        "200":
          description: "Notes list successfully retrieved"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/List-NoteResponse"
      deprecated: false
      security:
      - matchme-jwt-auth: []
    parameters: []
  /api/v1/notes/create:
    post:
      tags:
      - "Notes repository"
      summary: "Create a note"
      description: "The endpoint for note creation given a title and a body"
      parameters: []
      requestBody:
        description: "Create a note"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateNoteRequest"
        required: true
      responses:
        "201":
          description: "Note successfully created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Boolean"
      deprecated: false
      security:
      - matchme-jwt-auth: []
    parameters: []
  /api/v1/notes/{noteId}:
    delete:
      tags:
      - "Notes repository"
      summary: "Delete a note"
      description: "The endpoint for note deletion given its id"
      parameters:
      - name: "noteId"
        in: "path"
        schema:
          type: "string"
        required: true
        deprecated: false
      responses:
        "200":
          description: "Note successfully deleted"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Boolean"
      deprecated: false
      security:
      - matchme-jwt-auth: []
    parameters: []
  /users/{id}:
    get:
      tags:
      - "Users repository"
      summary: "Get a user"
      description: "User retrieval endpoint"
      parameters:
      - name: "id"
        in: "path"
        schema:
          type: "string"
        required: true
        deprecated: false
      responses:
        "200":
          description: "User successfully retrieved"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserData"
        "404":
          description: "User not found"
        "400":
          description: "User request is inavlid"
      deprecated: false
      security:
      - matchme-jwt-auth: []
    put:
      tags:
      - "Users repository"
      summary: "Update a user"
      description: "User update endpoint"
      parameters:
      - name: "id"
        in: "path"
        schema:
          type: "string"
        required: true
        deprecated: false
      requestBody:
        description: "Update a user"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserData"
        required: true
      responses:
        "200":
          description: "User successfully updated"
        "400":
          description: "User update request is invalid"
      deprecated: false
      security:
      - matchme-jwt-auth: []
    delete:
      tags:
      - "Users repository"
      summary: "Delete a user"
      description: "User deletion endpoint"
      parameters:
      - name: "id"
        in: "path"
        schema:
          type: "string"
        required: true
        deprecated: false
      responses:
        "200":
          description: "User successfully deleted"
        "400":
          description: "User deletion request is invalid"
      deprecated: false
      security:
      - matchme-jwt-auth: []
    parameters: []
webhooks: {}
components:
  schemas:
    TokenData:
      type: "object"
      properties:
        accessToken:
          type: "string"
        refreshToken:
          type: "string"
      required:
      - "accessToken"
      - "refreshToken"
    UserLoginRequest:
      type: "object"
      properties:
        email:
          type: "string"
        password:
          type: "string"
      required:
      - "email"
      - "password"
    RefreshToken:
      type: "object"
      properties:
        token:
          type: "string"
      required:
      - "token"
    SignupResponse:
      type: "object"
      properties:
        emailSent:
          type: "boolean"
        message:
          type: "string"
      required:
      - "emailSent"
      - "message"
    UserData:
      type: "object"
      properties:
        email:
          type: "string"
        id:
          type: "string"
        verified:
          type: "boolean"
      required:
      - "email"
      - "id"
      - "verified"
    NoteResponse:
      type: "object"
      properties:
        body:
          type: "string"
        id:
          type: "string"
        title:
          type: "string"
      required:
      - "body"
      - "id"
      - "title"
    List-NoteResponse:
      items:
        $ref: "#/components/schemas/NoteResponse"
      type: "array"
    Boolean:
      type: "boolean"
    CreateNoteRequest:
      type: "object"
      properties:
        body:
          type: "string"
        title:
          type: "string"
      required:
      - "body"
      - "title"
  securitySchemes:
    matchme-jwt-auth:
      bearerFormat: "JWT"
      type: "http"
      scheme: "bearer"
security: []
tags: []
